server:
  port: 8080

ai:
  enabled: false
  provider: local
  model: o3-mini
  role: user
  apiKey: ''
  endpoint: ''
  temperature: ''
  tokens: 0.7 # max tokens

git:
  provider: github  # Change to 'azure' for Azure DevOps
  token: YOUR_GITHUB_TOKEN
  url: '' # base url to git
  organization: '' # for
  project: ''
  version: '' # for Azure like 7.1-preview.1

  azure:
    token: YOUR_AZURE_DEVOPS_TOKEN
    org: your-org
    project: your-project
    repo: your-repo

# todo ?all analyzer ...
sonar:
  fetch: true # fetch result from sonar or scan files
  host: http://localhost:9000
  token: YOUR_SONARQUBE_TOKEN

checkstyle:
  config: |
    <?xml version="1.0"?>
    <!DOCTYPE module PUBLIC "-//Checkstyle//DTD Checkstyle Configuration 1.3//EN"
    "https://checkstyle.sourceforge.io/dtds/configuration_1_3.dtd">
    <module name="Checker">
        <module name="TreeWalker">
            <module name="UnusedImports"/>
            <module name="AvoidStarImport"/>
            <module name="FinalClass"/>
            <module name="ConstantName"/>
            <module name="MethodName"/>
            <module name="Indentation"/>
            <module name="ParameterName"/>
            <module name="WhitespaceAround"/>
        </module>
    </module>

pmd:
  rules: |
    <ruleset name="Custom Rules" xmlns="http://pmd.sourceforge.net/ruleset/2.0.0"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:schemaLocation="http://pmd.sourceforge.net/ruleset/2.0.0
      http://pmd.sourceforge.net/ruleset_2_0_0.xsd">
    
      <rule ref="category/java/bestpractices.xml"/>
      <rule ref="category/java/performance.xml"/>
      <rule ref="category/java/errorprone.xml"/>
    </ruleset>